services:
  maintenance:
    image: docker.lechner-systems.at/lechnersystems/maintenance:${IMAGE_TAG:-latest}
    restart: unless-stopped
    dns:
      - 192.168.100.2
      - 192.168.100.6
    ports:
      - "${MAIN_PORT:-8080}:80"
