services:
  portfolio:
    image: docker.lechner-systems.at/lechnersystems/maintenance:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    dns:
      - 192.168.100.2
      - 192.168.100.6
    ports:
      - "${MAIN_PORT:-8080}:80"
